sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
branches:
  only:
  - master
env:
  global:
    secure: TcH8ja8PCbBjf+c1qcu5cAxSM+VSBYbcgkMYFo9Kya2XYrn/+feYC6hFXDZ0m9fLry0qP141Bb9g14lSY0xmp7JmixDEH9BIMq7Yb9qs4/MllnEi2h3moK3KRDezi9cGuSMYpGNKymzQud/uyfdlon5f14jEH8OlSPdoA/0qBR6BveybMJRcX6VkZJUzw1N9ybo3eRFrMZ0uQSYsLQtDGHCcfdUtmXPARk0IRR/7dBeeVSCpZV2EtJTH89mFoFqF51vHCuQTOW4l7T2+zwXeVyn0nCQXmCUy0QDLd/WXnua7Ht47N3PfvEfHPTsy4NtkuB+teRN+2U8OyFUZtor7ijhAjmqjn4FdUy6kKdg6QAuQSMVumPRx2H6dJsETeMvdAFQGEKx3Gqgaej9xWanYnDBUFM6BHZpSKLzMgMl/qvQgB0IEj9gqzS6LebGrEmYAuUcqz4sd/ndJbGGixadJPAa5X1YkPAc2skOLTLeNbdUo/CK7UwvSli0p3uPDlEMElNCXb2Io9YJb8YdMrtbk0NbCfWzjuPfC+maP5xfniak6f0WV5DBfJW33zyDlzD/4VTr6r0ee51RLso88uNhuEefwjXbGDuMforwa+FaxOGaqmC19gOVrtQHMWNvIrvtE44PSyeN4rjeaEkXHlBtnBuo68/fZeo30xe4OV53Uy+o=
